name: Deploy
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubActionsRole
  CDK_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/CdkDeployRole

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Packages
        shell: bash
        run:  npm ci

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Version Check
        shell: bash
        run: npm run cdk -- --version

      - name: CDK Diff Check
        shell: bash
        run: npm run cdk diff -- -c AWS_ACCOUNT=${{ env.AWS_ACCOUNT }} --all

      - name: CDK Deploy
        shell: bash
        run: |
          npm run cdk deploy -- \
            -c AWS_ACCOUNT=${{ env.AWS_ACCOUNT }} \
            --all \
            --require-approval never \
            --role-arn ${{ env.CDK_ROLE_ARN }}